name: Build/Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse All Secrets
        run: |
          SECRETS="$${ toJson(secrets) }}"
          $( echo "$values" | jq -r 'keys[] as $k | "export \($k)=\(.[$k])" >> .env' )
          cat .env
