name: Build/Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse All Secrets
        run: jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$secrets" > .env
        env:
          secrets: ${{ toJson(secrets) }}
      - name: Display env file
        run: cat .env
